src/main/java/sk/pgl/spring/dto/ForgotPasswordForm.java
package sk.pgl.spring.dto;

import sk.pgl.spring.entities.User;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

public class ForgotPasswordForm {
    @NotNull
    @Size(min = 1, max = User.EMAIL_MAX, message = "{emailSizeError}")
    @Pattern(regexp = User.EMAIL_REGEX, message = "{emailPatternError}")
    private String email = "";

    public ForgotPasswordForm() {
    }

    public ForgotPasswordForm(String email) {
        this.email = email;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public String toString() {
        return "ForgotPasswordForm{" +
                "email='" + email + '\'' +
                '}';
    }
}

src/main/java/sk/pgl/spring/dto/ResetPasswordForm.java
package sk.pgl.spring.dto;

import sk.pgl.spring.entities.User;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

public class ResetPasswordForm {
    @NotNull
    @Size(min = 1, max = User.PASSWORD_MAX, message = "{passwordSizeError}")
    private String password = "";

    @NotNull
    @Size(min = 1, max = User.PASSWORD_MAX, message = "{passwordSizeError}")
    private String retypePassword = "";

    public ResetPasswordForm() {
    }

    public ResetPasswordForm(String password, String retypePassword) {
        this.password = password;
        this.retypePassword = retypePassword;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getRetypePassword() {
        return retypePassword;
    }

    public void setRetypePassword(String retypePassword) {
        this.retypePassword = retypePassword;
    }

    @Override
    public String toString() {
        return "ResetPasswordForm{" +
                "password='" + password + '\'' +
                ", retypePassword='" + retypePassword + '\'' +
                '}';
    }
}

src/main/java/sk/pgl/spring/dto/SignupForm.java
package sk.pgl.spring.dto;

import sk.pgl.spring.entities.User;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

public class SignupForm {
    @NotNull
    @Size(min = 1, max = User.EMAIL_MAX, message = "{emailSizeError}")
    @Pattern(regexp = User.EMAIL_REGEX, message = "{emailPatternError}")
    private String email;

    @NotNull
    @Size(min = 1, max = User.NAME_MAX, message = "{fieldSizeError}")
    private String name;

    @NotNull
    @Size(min = 1, max = User.PASSWORD_MAX, message = "{passwordSizeError}")
    private String password;

    public SignupForm() {
    }

    public SignupForm(String email, String name, String password) {
        this.email = email;
        this.name = name;
        this.password = password;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public String toString() {
        return "SignupForm{" +
                "email='" + email + '\'' +
                ", name='" + name + '\'' +
                ", password='" + password + '\'' +
                '}';
    }
}

src/main/java/sk/pgl/spring/dto/UserEditForm.java
package sk.pgl.spring.dto;

import sk.pgl.spring.entities.User;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.util.Set;

public class UserEditForm {
    @NotNull
    @Size(min = 1, max = User.NAME_MAX, message = "{fieldSizeError}")
    private String name = "";

    private Set<User.Role> roles;

    public UserEditForm() {
    }

    public UserEditForm(String name, Set<User.Role> roles) {
        this.name = name;
        this.roles = roles;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set<User.Role> getRoles() {
        return roles;
    }

    public void setRoles(Set<User.Role> roles) {
        this.roles = roles;
    }

    @Override
    public String toString() {
        return "UserEditForm{" +
                "name='" + name + '\'' +
                ", roles=" + roles +
                '}';
    }
}

src/main/java/sk/pgl/spring/entities/User.java
package sk.pgl.spring.entities;

import sk.pgl.spring.util.MyUtil;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

@Entity
@Table(name = "usr", indexes = {
        @Index(columnList = "email", unique = true),
        @Index(columnList = "forgotPasswordCode", unique = true)
})
public class User {
    public static final int EMAIL_MAX = 250;
    public static final int NAME_MAX = 50;
    public static final int PASSWORD_MAX = 30;
    public static final int RANDOM_CODE_LENGTH = 16;
    public static final String EMAIL_REGEX = "[A-Za-z0-9._%-+]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}";

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    @Column(nullable = false, length = EMAIL_MAX)
    private String email;

    @Column(nullable = false, length = NAME_MAX)
    private String name;

    @Column(nullable = false)
    private String password;

    @ElementCollection(fetch = FetchType.EAGER)
    private Set<Role> roles = new HashSet<>();

    @Column(length = RANDOM_CODE_LENGTH)
    private String verificationCode;

    @Column(length = RANDOM_CODE_LENGTH)
    private String forgotPasswordCode;

    public User() {
    }

    public User(String email, String name, String password) {
        this.email = email;
        this.name = name;
        this.password = password;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Set<Role> getRoles() {
        return roles;
    }

    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }

    public String getVerificationCode() {
        return verificationCode;
    }

    public void setVerificationCode(String verificationCode) {
        this.verificationCode = verificationCode;
    }

    public String getForgotPasswordCode() {
        return forgotPasswordCode;
    }

    public void setForgotPasswordCode(String forgotPasswordCode) {
        this.forgotPasswordCode = forgotPasswordCode;
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", email='" + email + '\'' +
                ", name='" + name + '\'' +
                ", password='" + password + '\'' +
                '}';
    }

    public boolean isAdmin() {
        return roles.contains(Role.ADMIN);
    }

    public boolean isEditable() {
        User loggedIn = MyUtil.getSessionUser();
        return loggedIn != null && (loggedIn.isAdmin() || loggedIn.getId() == id);
    }

    public enum Role {
        UNVERIFIED, BLOCKED, ADMIN
    }
}

src/main/java/sk/pgl/spring/controllers/UserController.java
package sk.pgl.spring.controllers;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;
import sk.pgl.spring.dto.UserEditForm;
import sk.pgl.spring.entities.User;
import sk.pgl.spring.services.UserService;
import sk.pgl.spring.util.MyUtil;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

@Controller
@RequestMapping("/users")
public class UserController {
    private static final Logger logger = LoggerFactory.getLogger(UserController.class);
    private UserService userService;

    @Autowired
    public void setUserService(UserService userService) {
        this.userService = userService;
    }

    @GetMapping("/{verificationCode}/verify")
    public String verify(@PathVariable("verificationCode") String verificationCode,
            RedirectAttributes redirectAttributes,
            HttpServletRequest httpServletRequest) throws ServletException {
        logger.warn("SOM TU 1");
        userService.verify(verificationCode);
        logger.warn("SOM TU 2");
        MyUtil.flash(redirectAttributes, "success", "verificationSuccess");
        logger.warn("SOM TU 3");
        httpServletRequest.logout();
        logger.warn("SOM TU 4");

        return "redirect:/";
    }

    @GetMapping("/{userId}")
    public String getById(@PathVariable("userId") long userId, Model model) {
        model.addAttribute(/*"user", */userService.findOne(userId));
        return "user";
    }

    @GetMapping("/{userId}/edit")
    public String edit(@PathVariable("userId") long userId, Model model) {
        User user = userService.findOne(userId);
        UserEditForm form = new UserEditForm();
        form.setName(user.getName());
        form.setRoles(user.getRoles());
        model.addAttribute(form);

        return "user-edit";
    }

    @PostMapping("/{userId}/edit")
    public String edit(@PathVariable("userId") long userId,
            @ModelAttribute("userEditForm") @Valid UserEditForm userEditForm,
            BindingResult result,
            RedirectAttributes redirectAttributes,
            HttpServletRequest request) throws ServletException {

        if (result.hasErrors()) {
            return "user-edit";
        }

        userService.update(userId, userEditForm);
        MyUtil.flash(redirectAttributes, "success", "editSuccessful");
        request.logout();

        return "redirect:/";
    }
}

src/main/webapp/WEB-INF/jsp/error.jsp
<%@include file="includes/header.jsp" %>
<div class="alert alert-danger">
    <p>There was an unexpected error (type=${error}, status=${status}): <i>${message}</i></p>
    <p>Click <a href="/">here</a> to go to home page</p>
</div>
<%@include file="includes/footer.jsp" %>

src/main/webapp/WEB-INF/jsp/forgot-password.jsp
<%@include file="includes/header.jsp" %>
<div class="panel panel-primary">

    <div class="panel-heading">
        <h3 class="panel-title">Forgot password?</h3>
    </div>

    <div class="panel-body">

        <form:form modelAttribute="forgotPasswordForm" role="form">

            <form:errors/>

            <div class="form-group">
                <form:label path="email">Email address</form:label>
                <form:input path="email" type="email" class="form-control" placeholder="Enter email"/>
                <form:errors cssClass="error" path="email"/>
                <p class="help-block">Please enter your email id</p>
            </div>

            <button type="submit" class="btn btn-default">Reset password</button>

        </form:form>
    </div>
</div>
<%@include file="includes/footer.jsp" %>

src/main/webapp/WEB-INF/jsp/home.jsp
<%@include file="includes/header.jsp"%>
        <spring:message code="hello" />
<%@include file="includes/footer.jsp"%>

src/main/webapp/WEB-INF/jsp/login.jsp
<%@include file="includes/header.jsp" %>

<div class="panel panel-primary">

    <div class="panel-heading">
        <h3 class="panel-title">Please sign in</h3>
    </div>

    <div class="panel-body">

        <c:if test="${param.error != null}">
            <div class="alert alert-danger">
                Invalid username and password.
            </div>
        </c:if>

        <c:if test="${param.logout != null}">
            <div class="alert alert-danger">
                You have been logged out.
            </div>
        </c:if>

        <form:form role="form" method="post">

            <div class="form-group">
                <label for="username">Email address</label>
                <input id="username" name="username" type="email" class="form-control" placeholder="Enter email"/>
                <p class="help-block">Enter your email address.</p>
            </div>

            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" id="password" name="password" class="form-control" placeholder="Password"/>
                <form:errors cssClass="error" path="password"/>
            </div>

            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input name="remember-me" type="checkbox"> Remember me
                    </label>
                </div>
            </div>

            <button type="submit" class="btn btn-primary">Sign In</button>
            <a class="btn btn-default" href="/forgot-password">Forgot password</a>

        </form:form>
    </div>
</div>

<%@include file="includes/footer.jsp" %>

src/main/webapp/WEB-INF/jsp/reset-password.jsp
<%@include file="includes/header.jsp" %>

<div class="panel panel-default">

    <div class="panel-heading">
        <h3 class="panel-title">Reset password</h3>
    </div>

    <div class="panel-body">

        <form:form modelAttribute="resetPasswordForm" role="form">

            <form:errors/>

            <div class="form-group">
                <form:label path="password">Type new password</form:label>
                <form:password path="password" class="form-control" placeholder="Password"/>
                <form:errors cssClass="error" path="password"/>
            </div>

            <div class="form-group">
                <form:label path="retypePassword">Retype new password</form:label>
                <form:password path="retypePassword" class="form-control" placeholder="Retype password"/>
                <form:errors cssClass="error" path="retypePassword"/>
            </div>

            <button type="submit" class="btn btn-default">Submit</button>

        </form:form>
    </div>
</div>

<%@include file="includes/footer.jsp" %>

src/main/webapp/WEB-INF/jsp/signup.jsp
<%@include file="includes/header.jsp" %>
<div class="panel panel-default">

    <div class="panel-heading">
        <h3 class="panel-title">Please signup</h3>
    </div>

    <div class="panel-body">

        <form:form modelAttribute="signupForm" role="form">
            <form:errors />

            <div class="form-group">
                <form:label path="email">Email address</form:label>
                <form:input path="email" type="email" class="form-control" placeholder="Enter email"/>
                <form:errors cssClass="error" path="email"/>
                <p class="help-block">Enter a unique email address. It will also be your login id.</p>
            </div>

            <div class="form-group">
                <form:label path="name">Name</form:label>
                <form:input path="name" class="form-control" placeholder="Enter name"/>
                <form:errors cssClass="error" path="name"/>
                <p class="help-block">Enter your display name.</p>
            </div>

            <div class="form-group">
                <form:label path="password">Password</form:label>
                <form:password path="password" class="form-control" placeholder="Password"/>
                <form:errors cssClass="error" path="password"/>
            </div>

            <button type="submit" class="btn btn-default">Submit</button>

        </form:form>
    </div>
</div>
<%@include file="includes/footer.jsp" %>

src/main/webapp/WEB-INF/jsp/user-edit.jsp
<%@include file="includes/header.jsp" %>
<div class="panel panel-primary">

    <div class="panel-heading">
        <h3 class="panel-title">Profile</h3>
    </div>

    <div class="panel-body">

        <form:form modelAttribute="userEditForm" class="form-horizontal" role="form">

            <div class="form-group">
                <form:label path="name" class="col-lg-2 control-label">Name</form:label>
                <div class="col-lg-10">
                    <form:input path="name" class="form-control" placeholder="Roles"/>
                    <form:errors cssClass="error" path="name"/>
                    <p class="help-block">Enter your display name.</p>
                </div>
            </div>

            <sec:authorize access="hasRole('ROLE_ADMIN')">
                <div class="form-group">
                    <form:label path="roles" class="col-lg-2 control-label">Roles</form:label>
                    <div class="col-lg-10">
                        <form:input path="roles" class="form-control" placeholder="Roles"/>
                        <form:errors cssClass="error" path="roles"/>
                        <p class="help-block">Enter the roles of the user, separated by commas</p>
                    </div>
                </div>
            </sec:authorize>

            <div class="form-group">
                <div class="col-lg-offset-2 col-lg-10">
                    <button type="submit" class="btn btn-primary">Update</button>
                </div>
            </div>

        </form:form>

    </div>

</div>
<%@include file="includes/footer.jsp" %>

src/main/webapp/WEB-INF/jsp/user.jsp
<%@include file="includes/header.jsp" %>

<div class="panel-heading">
    <h3 class="panel-title">Profile</h3>
</div>

<div class="panel-body">
    <dl class="dl-horizontal">
        <dt>Name</dt>
        <dd><c:out value="${user.name}"/></dd>
        <dt>Email</dt>
        <dd><c:out value="${user.email}"/></dd>
        <dt>Roles</dt>
        <dd><c:out value="${user.roles}"/></dd>
    </dl>
</div>

<c:if test="${user.editable}">
    <div class="panel-footer">

        <a class="btn btn-link" href="/users/${user.id}/edit">Edit</a>
        <a class="btn btn-link" href="/users/${user.id}/change-password">Change password</a>
        <a class="btn btn-link" href="/users/${user.id}/change-email">Change email id</a>
        <!-- TODO implement these features -->
    </div>
</c:if>

<%@include file="includes/footer.jsp" %>